### PR TITLE
Added functionality to show only 1 notification at a time and hide no…

### PR DESCRIPTION
**Pull request by m-irfan**
…tification option

### CODE REVIEW

**Comment by casperriboe** [comment]
Hey, thanks for the PR.

What are your thoughts behind this PR? You haven't put any description of it.
There are some stuff that doesn't quite make sense. First off, you create an array of `CRNotification` views that essentially never hold more than one element, since you can `removeAll` every time a notification is created. Here it would make sense to just keep _one_ optional notification instead of a list.

The method `isNotificationVisible` can just return the first condition as a result instead, which is a little cleaner. Your check for an empty array which should be done through `isEmpty` for better readability. But what might be better would be to use `currentNotification?.superview != nil` provided that the implementation relies on a single notification instead of a list.

If however, a list is used, this could maybe provide a queue system where the next notification in line would be displayed, when the other is dismissed. Or maybe decide when presenting the notification, whether or not the given notification should be allowed displayed onto of the other or not based on whether a notification is actually present at the given time. In this way, a promotion system is implemented and one notification can actually be more important than others. If for some reason you'd go the extra mile, a notification call or `CRNotificationType` could actually have a priority value that decides whether or not the notification is allowed to be presented over the one that is already on screen.

**Comment by m-irfan** [comment]
Hello Casper Riboe

This is my first ever PR in any Github project so please don’t mind and ignore it, I was not expecting quick response on it, but you are great and thanks for responding. I liked CRNotification very much that’s why I decided to modify it as per my requirement, but I know this change is not required for all developers.

But I think I can improve it as per your suggestions and make it flexible. I can add option where user can mention to choose between displaying one notification at a time or allowing multiple notifications. But hiding this notification without tapping was missing I think this feature you should implement in it, this is just my suggestion.

Thanks
Best Regards
Irfan Anwar

On 11-Apr-2018, at 4:43 PM, Casper Riboe <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, thanks for the PR.

What are your thoughts behind this PR, you haven't put any description of it.
There are some stuff that doesn't quite make sense. First off, you create an array of CRNotification views that essentially never hold more than one element, since you can removeAll every time a notification is created. Here it would make sense to just keep one optional notification instead of a list.

The method isNotificationVisible can just return the first condition as a result instead, which is a little cleaner. You check for an empty array which should be done through isEmpty for better readability. But what might be better would be to use currentNotification?.superview != nil provided that the implementation relies on a single notification instead of a list.

If however, a list is used, this could maybe provide a queue system where the next notification in line would be displayed, when the other is dismissed. Or maybe decide when presenting the notification, whether or not the given notification should be allowed displayed or not based on whether a notification is actually present at the given time. In this way, a promotion system is implemented and one notification can actually be more important than others. If for some reason you'd go the extra mile, a notification or CRNotificationType could actually have a priority value that decides whether or not the notification is allowed to be presented over the one that is already on screen.

**Comment by dkcas11** [comment]
Hey, no worries. 
Try and customize it to allow users to decide whether one should be allowed at a time or not :-)

**Comment by dkcas11** [comment]
This is now implemented (not from this PR).

**Pull request closed without merging**
