### PR TITLE
Custom Background Color and swipe up

### PR DESCRIPTION
**Pull request by xremix**
Hey

this library works great for my project. However the styles don't fit the theme of my App. So I build a little extension that allows to pass a custom background color.

This is more a solution to get my problem fixed. A better solution might be, to let the CRNotificationType be a Class that include the color (and maybe border, shadows, etc.). There could be a couple of static variables that return the defaults for info, error, etc., that will be passed as a parameter, but user could still create a new instance with custom properties.
I could work on something like this, if you see this benefitial.

### CODE REVIEW

**Comment by xremix** [comment]
Just seeing, that instead of having the second solution I mentioned it would make sense to just create an instance of `CRNotification` like the `showNotification()` function is doing. So forget about the second part :)

Still I see benefits with my PR, so people can just use this as a one-liner.

**Comment by xremix** [comment]
Also, would it make sense to let the `CRNotification` class be public, so people could create custom instances or write their own `showNotification()` function?

**Comment by dkcas11** [comment]
Hey, thanks for your PR 🙂 

I have actually had the intention of adding this myself but I never got to do it. (I am not sure if I actually did it, but never put it up here)

The way to do this would be to just take a protocol as a parameter which any struct or class can implement, returning the correct image and colours.

The project could use a little spring cleaning, so I might as well do that to it.

I like the addition of the swipe gesture.

**Comment by anthonycastelli** [comment]
What is the status of this PR? I like the idea of the Swipe, and the ability to change colors would be ideal.

**Comment by dkcas11** [comment]
@anthonycastelli I have the project on my Mac where this is done and where I have expanded on the implementation to allow for better custom styling. I have yet to decide on further additions but I can put it up here tomorrow and you guys can come with some inputs on that maybe.

**Comment by xremix** [comment]
@dkcas11 I was trying to implement an solution by using a protocol, but had some issues with that, so I didn't commit these changes.
I'd love to review your changes and give you my input. This is really beneficial to me.

**Comment by xremix** [comment]
@dkcas11 do you want me to open a separate PR for the swipe up?

**Comment by dkcas11** [comment]
@xremix I have done the exact thing, and implemented a protocol for anyone to implement and customize their notifications. This wasn't the intention originally, since i just wanted it to be easy to use, but what i really just got was the shortcut like `.success` when passing a notification type. So this now needs to be passed as `CRNotifications.success` or something like that.
As i said, i have it on my Mac at home (on the working MBP right now), so i will put up the PR in about an hour once i am home and ping you 🙂

**Comment by dkcas11** [comment]
@xremix [PR](https://github.com/dkcas11/CRNotifications/pull/13) is up 👍

**Comment by dkcas11** [comment]
Now implemented (not from this PR).

**Pull request closed without merging**
